---
abstract: 'Automatic number guessing game robot'
author:
  - 'imacat <imacat@mail.imacat.idv.tw>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-GuessNumber
no_index:
  directory:
    - t
    - inc
requires: {}
version: 0.04
